version: "3.9"
services:
  nodejs:
    image: node:16
    container_name: nodejs
    volumes:
      - ./:/app
    command: ["bash","-c","apt-get -y update && apt-get -y install default-jre && apt-get -y -f install && apt-get install -y chromium-browser && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install -y ./google-chrome-stable_current_amd64.deb"]
    entrypoint: bash
    tty: true
    # expose: [8080]
    # ports:
    #   - 8080:4200