version: "3.9"
services:
  nodejs:
    image: node:16
    container_name: nodejs
    volumes:
      - ./:/app
    entrypoint: [bash""apt-get update && apt-get install default-jre && apt-get -f install && apt-get install chromium-browser && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install ./google-chrome-stable_current_amd64.deb"]
    tty: true
    # expose: [8080]
    # ports:
    #   - 8080:4200